tap 'bramstein/webfonttools'
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/php'
tap 'homebrew/services'
tap 'homebrew/versions'
cask 'java'
brew 'ack'
brew 'openssl'
brew 'readline'
brew 'sqlite'
brew 'aircrack-ng'
brew 'autoconf'
brew 'automake'
brew 'bash'
brew 'bash-completion'
brew 'bfg'
brew 'binutils'
brew 'cifer'
brew 'coreutils'
brew 'dark-mode'
brew 'dex2jar'
brew 'diff-so-fancy'
brew 'libgpg-error'
brew 'libassuan'
brew 'libgcrypt'
brew 'libksba'
brew 'pth'
brew 'dirmngr'
brew 'dns2tcp'
brew 'dnsmasq'
brew 'fcrackzip'
brew 'figlet'
brew 'findutils'
brew 'foremost'
brew 'libpng'
brew 'freetype'
brew 'gettext'
brew 'git'
brew 'git-lfs'
brew 'gmp'
brew 'gnu-sed', args: ['with-default-names']
brew 'gnu-tar'
brew 'pinentry'
brew 'gpg-agent'
brew 'libusb'
brew 'libusb-compat'
brew 'gnupg2'
brew 'go'
brew 'hashpump'
brew 'hub'
brew 'icu4c'
brew 'jpeg'
brew 'libtiff'
brew 'libtool'
brew 'xz'
brew 'imagemagick', args: ['with-webp']
brew 'isl'
brew 'isl@0.14'
brew 'jasper'
brew 'john'
brew 'knock'
brew 'libdnet'
brew 'libidn'
brew 'mpfr'
brew 'libmpc'
brew 'libxml2'
brew 'libyaml'
brew 'lua'
brew 'lynx'
brew 'lzo'
brew 'makedepend'
brew 'mas'
brew 'md5sha1sum'
brew 'moreutils'
brew 'netpbm'
brew 'ngrep'
brew 'nmap'
brew 'node'
brew 'openvpn', restart_service: true
brew 'p7zip'
brew 'pcre'
brew 'pigz'
brew 'pkg-config'
brew 'pngcheck'
brew 'pre-commit'
brew 'pv'
brew 'rename'
brew 'ruby'
brew 'socat'
brew 'speedtest_cli'
brew 'sqlmap'
brew 'ssh-copy-id'
brew 'tcpflow'
brew 'tcpreplay'
brew 'tcptrace'
brew 'testssl'
brew 'tree'
brew 'ucspi-tcp'
brew 'unixodbc'
brew 'vbindiff'
brew 'vim', args: ['with-override-system-vi']
brew 'webkit2png'
brew 'webp'
brew 'wget'
brew 'zopfli'
brew 'bramstein/webfonttools/sfnt2woff'
brew 'bramstein/webfonttools/sfnt2woff-zopfli'
brew 'bramstein/webfonttools/woff2'
brew 'homebrew/dupes/grep'
brew 'homebrew/dupes/openssh'
brew 'homebrew/dupes/screen'
brew 'homebrew/php/php71'
cask 'dropbox'
cask 'phpstorm'
cask 'robomongo'
cask 'sequel-pro'
cask 'skype'
cask 'sublime-text'
cask 'vagrant'
cask 'virtualbox'
cask 'webstorm'
mas 'Aperture', id: 408981426
mas 'Xcode', id: 497799835
mas 'Keynote', id: 409183694
mas 'Kindle', id: 405399194
mas 'Twitter', id: 409789998
mas '1Password', id: 443987910
mas 'Tyme2', id: 1063996724
mas 'Slack', id: 803453959
mas 'Pages', id: 409201541
mas 'Numbers', id: 409203825
mas 'Deckset', id: 847496013
